### ISSUE TITLE
Fails with ES6 spread operator

### ISSUE THREAD

**Issue by kbherbert** [justinwilaby/grunt-jspm-builder#2]
Thanks for sharing this plugin. I think it's really great!

However, I did run into an issue where the build would fail due to line 45:

``` javascript
    commonTree = warn ? traces[0] : builder.intersectTrees(...traces);
```

The ES6 spread operator wasn't stabilized until Node v5. Therefore, for users in older versions of node (I am on v4) there are 2 options:
1.  Pass the --harmony flag to run Node with "staged" features
2. Or, you can update the repo to not use the spread operator and instead do something like:

``` javascript
    commonTree = warn ? traces[0] : builder.intersectTrees.apply(null, traces);
```

**Comment by kbherbert** [comment]
@justinwilaby Your thoughts?

**Comment by justinwilaby** [comment]
@kbherbert - I am fine updating the plugin to use Node >=4.0.  It should be a simple change.  I'll have it in shortly.

**Comment by kbherbert** [comment]
Cool, thanks. Yea actually I just tried running in --harmony mode (option #1 above) and while that resolves the primary issue, it introduced another somewhere.

**Comment by justinwilaby** [comment]
Pull down the latest and test.  If it's working for you, I'll resolve this issue.

**Comment by kbherbert** [comment]
Yep, all good. Thank you sir!
