### ISSUE TITLE
bundling fails with 0.17

### ISSUE THREAD

**Issue by selfagency** [justinwilaby/grunt-jspm-builder#5]
this `const expression = file.orig.src[0].replace(/\.js/, "");` causes the bundle to fail because it wants the .js extension

**Comment by justinwilaby** [comment]
I'll have a look. This task doesn't officially support v0.17. It might be time to add it.

**Comment by selfagency** [comment]
Just following up to see if you had a chance to do this yet

**Comment by selfagency** [comment]
since this stalled out, i've switched to just bundling using grunt-exec and the jspm cli.
